# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 15:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mailing_lists', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
            ],
        ),
    ]
