# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 11:20
from __future__ import unicode_literals

import dc_signup_form.signup_server.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupqueue',
            name='data',
            field=dc_signup_form.signup_server.models.BackwardsCompatibleJSONField(),
        ),
        migrations.AlterField(
            model_name='signupqueue',
            name='mailing_lists',
            field=dc_signup_form.signup_server.models.BackwardsCompatibleJSONField(),
        ),
    ]
