sudo: required
dist: trusty
language: python
python:
  - '3.4'
  - '3.5'
env:
  matrix:
    - DJANGO_VERSION='>=1.8,<1.9' POSTGRES_VERSION=9.3
    - DJANGO_VERSION='>=1.9,<1.10' POSTGRES_VERSION=9.3
    - DJANGO_VERSION='>=1.10,<1.11' POSTGRES_VERSION=9.3
    - DJANGO_VERSION='>=1.11,<1.12' POSTGRES_VERSION=9.3
    - DJANGO_VERSION='>=1.8,<1.9' POSTGRES_VERSION=9.5
    - DJANGO_VERSION='>=1.9,<1.10' POSTGRES_VERSION=9.5
    - DJANGO_VERSION='>=1.10,<1.11' POSTGRES_VERSION=9.5
    - DJANGO_VERSION='>=1.11,<1.12' POSTGRES_VERSION=9.5
before_install:
  - echo $POSTGRES_VERSION
  - sudo service postgresql stop && sudo service postgresql start $POSTGRES_VERSION
  - psql -U postgres -tc 'SHOW server_version'
install:
  - python setup.py install
  - pip install --upgrade pip
  - pip install -r testing_requirements.txt
  - "pip install Django$DJANGO_VERSION"
script:
  - coverage run --source=dc_signup_form --omit=dc_signup_form/tests/*.py,dc_signup_form/signup_server/tests/*.py,dc_signup_form/signup_server/migrations/*.py ./run_tests.py
after_success:
  - coveralls
