sudo: required
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'

env:
  matrix:
    - DJANGO_VERSION='>=2.2,<2.3' POSTGRES_VERSION=10
    - DJANGO_VERSION='>=3.2,<3.3' POSTGRES_VERSION=10
    - DJANGO_VERSION='>3.2' POSTGRES_VERSION=10
before_install:
  - echo $POSTGRES_VERSION
  - sudo service postgresql stop && sudo service postgresql start $POSTGRES_VERSION
  - psql -U postgres -tc 'SHOW server_version'
install:
  - python setup.py install
  - pip install --upgrade pip
  - pip install -r testing_requirements.txt
  - "pip install Django$DJANGO_VERSION"
script:
  - coverage run --source=dc_signup_form --omit=dc_signup_form/tests/*.py,dc_signup_form/signup_server/tests/*.py,dc_signup_form/signup_server/migrations/*.py ./run_tests.py
after_success:
  - coveralls
