sudo: false
dist: trusty
language: python
python:
  - '3.4'
  - '3.5'
env:
  matrix:
    - DJANGO_VERSION='>=1.8,<1.9'
    - DJANGO_VERSION='>=1.9,<1.10'
    - DJANGO_VERSION='>=1.10,<1.11'
    - DJANGO_VERSION='>=1.11,<1.12'
install:
  - python setup.py install
  - pip install --upgrade pip
  - pip install -r testing_requirements.txt
  - "pip install Django$DJANGO_VERSION"
script:
  - coverage run --source=dc_signup_form --omit=dc_signup_form/tests/*.py,dc_signup_form/signup_server/migrations/*.py ./run_tests.py
after_success:
  - coveralls
